stages:
  - build
  - lint
  - static
  - test
  - release

build_job:
  stage: build
  script:
    - echo "Building project"

lint_backend:
  stage: lint
  image: python
  before_script:
  #Add requirements.txt for lint to run
  script:
      - echo "Linting project"


static_backend:
  stage: static
  image: python
  before_script:
    #Add pip install - ./requirements.txt
  script:
    - echo "static analysis"
    #- mypy
  tags:
    - dind

#Unit test for backend
test_backend:
  stage: test
  image: python
  before_script:
    #pip install -r ./requirements.txt
  script:
    #this should run the integrated django tests
    coverage run --omit=manage.py,*/tests.py,*/migrations/*,*/settings.py manage.py test

  after_script:
    #record results

#Unit test for frontend
test_frontend:
  stage: test
  script:
      -echo "Testing Front End"


