stages:
  - lint
  - static
  - test
  - release

lint_backend:
  stage: lint
  image: python
  before_script:
    - pip install -r ./am_framework/requirements.txt
  script:
    - echo "Linting project"
    - black . --check --verbose --diff --color


static_backend:
  stage: static
  image: python
  before_script:
    - pip install -r ./am_framework/requirements.txt
  script:
    - echo "static analysis"
    - mypy . --ignore-missing-imports

  tags:
    - dind

#Unit test for backend
test_backend:
  stage: test
  image: docker:latest
  services:
  - "docker:dind"
  before_script:
    - docker compose build

  script:
    #this should run the integrated django tests
    - echo "Docker Containers Created - Starting Tests"
    - docker compose up --abort-on-container-exit

  after_script:
    #record results

#Unit test for frontend
#Not functional, front end tests are not complete
test_frontend:
  stage: test
  image: node:latest
  script:
    - echo "Testing Front End"
    - cd aircraft-manager-frontend
    - npm install
    - npm test


