version: "3"
services:
  #Database Service
  db:
    image: mysql:latest
    container_name: projectMySQLDb
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "aircraft_manager"
      MYSQL_ROOT_PASSWORD: "thePassword506"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "1qaz2wsx"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL"]
      timeout: "5s"
      retries: 5
  #Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangoContainer
    command: sh -c "cd am_framework && python3 manage.py migrate"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  data: