version: "3"
services:
  #Database Service
  db:
    image: mysql:5.7
    container_name: projectMySQLDb
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "aircraft_manager"
      MYSQL_ROOT_PASSWORD: "thePassword506"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "1qaz2wsx"
    ports:
      - "3306:3306"
  #Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangoContainer
    command: sh -c "python3 manage.py migrate"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
volumes:
  step: