# Generated by Django 5.0.3 on 2024-04-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_aircrafttable_userid_alter_airporttable_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementtable",
            name="arrivalDate",
            field=models.DateTimeField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="movementtable",
            name="departureDate",
            field=models.DateTimeField(max_length=8, null=True),
        ),
    ]
